global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'express-app'
    static_configs:
      - targets: ['192.168.50.11:3030']

  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['192.168.50.11:8888']
