global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'express-app'
    static_configs:
      - targets: ['<IP_OF_THE_MACHINE>:3030']

  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['<IP_OF_THE_MACHINE>:8888']
