services:
  express-app:
    build: .
    container_name: express-app
    ports:
      - "3030:3030"
    volumes:
      - ./logs:/app/logs

  promtail:
    image: grafana/promtail:2.9.1
    container_name: express-app-promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - ./logs:/var/log/app:ro
    command: -config.file=/etc/promtail/promtail-config.yml
