services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8888:8888"
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=info

  promtail:
    image: grafana/promtail:2.9.1
    container_name: fastapi-app-promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - ./logs:/var/log/app:ro
    command: -config.file=/etc/promtail/promtail-config.yml
